\set ON_ERROR_STOP
BEGIN;

CREATE TABLE yacht_raw (
    artist text,
    album text,
    title text,
    personnel_type text,
    name text,
    score numeric(5,2)
);

\copy yacht_raw from yacht.csv with csv header

create table songs (id int generated by default as identity primary key, artist text, title text, score numeric(5,2));
insert into songs (artist,title,score) (select distinct artist, title, score from yacht_raw);

create table performers (id int generated by default as identity primary key, name text);
select setval('performers_id_seq', 1000);
insert into performers (name) (select distinct name from yacht_raw);

create table nodes (id int, node_name text, node_type text);
insert into nodes (id,node_name,node_type) (select id, name, 'performer' from performers);
insert into nodes (id,node_name,node_type) (select id, title || ' - ' || artist, 'song' from songs);

create table node_map (id int generated by default as identity primary key, source int, target int, cost numeric(5,2));
insert into node_map (source,target,cost) (select distinct s.id as song_id, p.id as performer_id, s.score from yacht_raw yr join songs s using (artist,title) join performers p using (name) where s.score >= 50);
insert into node_map (source,target,cost)  (select target as source, source as target, cost from node_map);
